# Generated by Django 5.0.6 on 2024-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sub_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
