# Generated by Django 5.0.6 on 2024-05-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_alter_submission_sub_file_alter_submission_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='order_num',
        ),
    ]
